services:
  api:
    image: myproject-api
    ports:
      - "5000:80"
    environment: 
      - APP_PASSWORD
      - CAR_RENTAL_CONNECTION_STRING
      - SECRET_KEY

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M