server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: travel_accommodation_platform_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: travel_accommodation_platform-api
          __path__: /var/log/myapp/*.txt
